#[test]
fn component_ui() {
    let t = trybuild::TestCases::new();
    t.pass("tests/ui/component_valid.rs");
    t.pass("tests/ui/component_directive_valid.rs");
    t.pass("tests/ui/component_dynamic_attr_valid.rs");
    t.pass("tests/ui/css_named_helper_valid.rs");
    t.pass("tests/ui/component_builder_valid.rs");
    t.pass("tests/ui/component_builder_render_valid.rs");
    t.pass("tests/ui/component_builder_fully_qualified_markup.rs");
    t.pass("tests/ui/component_builder_foreign_markup.rs");
    t.pass("tests/ui/component_builder_repeated_markup.rs");
    t.pass("tests/ui/component_builder_defaulted_repeated.rs");
    t.pass("tests/ui/component_builder_defaulted_optional.rs");
    t.pass("tests/ui/component_builder_maybe_optional.rs");
    t.pass("tests/ui/component_builder_raw_identifier.rs");
    t.pass("tests/ui/slot_valid.rs");
    t.compile_fail("tests/ui/component_builder_missing_required.rs");
    t.compile_fail("tests/ui/component_builder_tuple_struct.rs");
    t.compile_fail("tests/ui/component_builder_duplicate_default_slot.rs");
    t.compile_fail("tests/ui/component_builder_each_non_vec.rs");
    t.compile_fail("tests/ui/component_builder_duplicate_maybe_method.rs");
    t.compile_fail("tests/ui/component_builder_raw_build.rs");
    t.compile_fail("tests/ui/component_builder_raw_render.rs");
    t.compile_fail("tests/ui/component_empty.rs");
    t.compile_fail("tests/ui/component_multiple_roots.rs");
    t.compile_fail("tests/ui/component_control_flow_root.rs");
    t.compile_fail("tests/ui/component_missing_helpers.rs");
    t.compile_fail("tests/ui/component_missing_js_helper.rs");
    t.compile_fail("tests/ui/component_missing_css_helper.rs");
    t.compile_fail("tests/ui/css_invalid_helper_name.rs");
    t.compile_fail("tests/ui/component_unknown_directive.rs");
    t.compile_fail("tests/ui/component_conflicting_directives.rs");
    t.compile_fail("tests/ui/component_directive_after_root.rs");
    t.compile_fail("tests/ui/component_trailing_tokens.rs");
}
